version: '3'
services:
  php:
    container_name: ec-sample_php
    build: ./docker/php
    volumes:
      - ./src:/var/www/src
  nginx:
    image: nginx
    container_name: ec-sample_nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: mysql:8.0
    container_name: ec-sample_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ec-sample
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  redis:
    container_name: ec-sample_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data

  mailhog:
    container_name: ec-sample_mailhog
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ec-sample_phpmyadmin
    ports:
      - 8001:80
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PMA_HOST: db
      MAX_EXECUTION_TIME: 3000
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M
